<?php

namespace Database\Seeders;

use App\Models\HomologacaoSolicitacao;
use Illuminate\Database\Seeder;

class HomologacaoSolicitacaoSeeder extends Seeder
{
    public function run()
    {
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Quando clica no logo do sistema vai para /index/404', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Acertar menu horizontal e colocar logo do sistema', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Não deixar escolher menu horizontal', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar RG do usuário na grade de Log Transações para fazer filtro (Pesquisar)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Contatos por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Ajudas de Custos por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Auxílios Fardamentos por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Cursos por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Dependentes por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Fundos de Saúde por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Férias por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Pensões por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar ordenação na Grade do submódulo Militares Tempos Averbados por Situação/Graduação/RG', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar botão para fechar perfil de Usuário abaixo da Fotografia', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar botão para fechar perfil de Militar abaixo da Fotografia', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Mostrar os dependentes do Militar na tela de Fundo de Saúde', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar opção de escolher Situação do Militar no relatório Efetivo (MILITARES POR GRADUAÇÃO)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar opção de escolher Situação do Militar no relatório Efetivo (MILITARES POR UNIDADE)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar opção de escolher Situação do Militar no relatório Efetivo (MILITARES POR QUADRO)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar opção de escolher Situação do Militar no relatório Efetivo (MILITARES POR COMPORTAMENTO)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar opção de escolher Situação do Militar no relatório Efetivo (MILITARES)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar opção de escolher Situação do Militar no relatório Efetivo (INFORMAÇÕES DO MILITAR)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Colocar informação no topo do Sistema: Sistema em Homologação', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Criar pequenos vídeos de explicação sobre o funcionamento do Sistema', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em ajuda de custo por movimentação: Inserir o campo: Nº Requerimento (Formato: xxxxx/xxxx) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em ajuda de custo por movimentação: Inserir o campo: Data Requerimento (Formato: xx/xx/xxxx) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em ajuda de custo por movimentação: Inserir o campo: Origem/Destino (Formato texto) - Preenchimento Obrigatório - Ou dois campos, um origem outro destino, fica a seu critério;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em ajuda de custo por curso: Inserir o campo: Nº Requerimento (Formato: xxxxx/xxxx) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em ajuda de custo por curso: Inserir o campo: Data Requerimento (Formato: xx/xx/xxxx) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em ajuda de custo por curso: Inserir o campo: Curso (Mesma relação da aba Cursos) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em ajuda de custo por curso: Inserir o campo: Boletim da Movimentação (Formato igual os demais Boletins) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em auxílio fardamento: Inserir o campo: Nº Requerimento (Formato: xxxxx/xxxx) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em auxílio fardamento: Inserir o campo: Data Requerimento (Formato: xx/xx/xxxx) - Preenchimento Obrigatório;', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Em auxílio fardamento: Inserir o campo: Data da última Promoção (Formato: xx/xx/xxxx) - Preenchimento Obrigatório; (Se possível)', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Se possível remover as opções de POR CURSO e POR MOVIMENTAÇÃO para auxílio fardamento.', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Corrigir a informação: ART. 64, da Lei 9537/2021 para ART. 64 da Lei 279/1979, alterado pela Lei 9537/2021.', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Situações para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Graduações para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Unidades para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Quadros para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Comportamentos para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Cursos para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Parentescos para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Funções para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Auxiliar Gêneros para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Contatos para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Ajudas de Custos para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Auxílios Fardamentos para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Cursos para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Dependentes para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Fundos Saúde para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Féris para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Pensões para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Militares Tempos Averbados para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Fazer alteração no código do Submódulo Tempos Averbados Locais para campo excluido', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Contatos', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Ajudas de Custos', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Auxílios Fardamentos', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Cursos', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Dependentes', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Fundos de Saúde', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Férias', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Pensões', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
        HomologacaoSolicitacao::create(['user_id' => 4, 'solicitacao' => 'Incluir Regras de Negócios (SAC antigo/Eduardo) no Submódulo Militares Tempos Averbados', 'solicitacao_tipo' => 'Melhoria', 'solicitacao_prioridade' => 'Normal', 'solicitacao_data' => date('Y-m-d'), 'solicitacao_hora' => date('H:i:s')]);
    }
}
